### ISSUE TITLE
ls -la command is wonky with the IDE

### ISSUE THREAD

**Issue by AnnJohn** [learn-co-curriculum/html-css-cli-basics#1]
"ls -a" and "ls -la," when entered in the IDE, cuts off the end of the command line prompt in the IDE. 

![screen shot 2016-06-06 at 11 42 32 am](https://cloud.githubusercontent.com/assets/1892150/15828055/cf039a76-2bdb-11e6-857d-715393b6d6ba.png)

If I press Enter enough times I can get to the bottom, but it's a weird user experience. 

@loganhasson @matbalez @pletcher

**Comment by loganhasson** [comment]
@AnnJohn looks like this is because you have the ide resized to be really narrow. if you leave it the full width of your screen, it should not behave like this. wrapping weirdly will still happen, but shouldn't go off the bottom of the screen.
