### ISSUE TITLE
open [file name] not working

### ISSUE THREAD

**Issue by AnnJohn** [learn-co-curriculum/html-css-cli-basics#2]
Following Grover's video, I tried to open a file that I had made via the command line, but couldn't get it to work. 

I tried `open index.html` (the file name), tried `learn open index.html` and `learn open` -- all the error messages are in the below screenshot. 

![screen shot 2016-06-06 at 11 57 39 am](https://cloud.githubusercontent.com/assets/1892150/15828591/f026a5ca-2bdd-11e6-8351-5d15cae278d0.png)

cc @loganhasson , @matbalez, @pletcher

**Comment by loganhasson** [comment]
@AnnJohn we'll need different instructions for IDE users. the `open` command doesn't work there. if users just want to view the text, they should either click on the file locally or run `atom index.html`. if they want to view in browser, they should right click on the file in the file tree, and select 'Open in Browser'

**Comment by AnnJohn** [comment]
thanks @loganhasson. I can't edit the video, but I'll add a note saying what you said above.

**Comment by AnnJohn** [comment]
updated
